name: Linter

on:
  push:
    branches:
      # long-lived branches
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
      - run: yarn lint
