name: Tests

on:
  push:
    branches:
      # long-lived branches
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.15.0"
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn
      - run: yarn test
        env:
          CI: true
